version: '3.1'

services:
  site:
    build:
      context: .
      args:
        - NODE_ENV=development

    command: ./node_modules/.bin/nodemon
    ports:
      - "8080:8080"
      - "9229:9229"

    volumes:
      - .:/usr/src/app:delegated # Used for nodemon working properly
    environment:
      - NODE_ENV=development
